language: python
python:
  - 2.7
install:
  - pip install pep8 --use-mirrors
  - python setup.py install
  - pip install https://github.com/dcramer/pyflakes/tarball/maste
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script:
  - python setup.py test -q
